### ISSUE TITLE
cuda

### ISSUE THREAD

**Issue by Ch180907** [yenchenlin/nerf-pytorch#117]
when I ran the project,encounter the following problems
Traceback (most recent call last):
  File "E:\Apps dates\pythonProject\NERF\nerf-pytorch-master\run_nerf.py", line 876, in <module>
    torch.set_default_tensor_type('torch.cuda.FloatTensor')
  File "D:\Apps\python\python3.11.1\Lib\site-packages\torch\__init__.py", line 606, in set_default_tensor_type
    _C._set_default_tensor_type(t)
TypeError: type torch.cuda.FloatTensor not available. Torch not compiled with CUDA enabled.
How can I solve it?

**Comment by Demonss3** [comment]
This indicates that your gpu version of pytorch was not installed successfully
