### ISSUE TITLE
TypeError: read() got an unexpected keyword argument 'ignoregamma' (Solution Provided)

### ISSUE THREAD

**Issue by JY251** [yenchenlin/nerf-pytorch#140]
I have encountered the following error. I have found a solution so I will share with you.
```
python run_nerf.py --config configs/fern.txt
Traceback (most recent call last):
  File "run_nerf.py", line 878, in <module>
    train()
  File "run_nerf.py", line 542, in train
    images, poses, bds, render_poses, i_test = load_llff_data(args.datadir, args.factor,
  File "/nerf-pytorch/load_llff.py", line 246, in load_llff_data
    poses, bds, imgs = _load_data(basedir, factor=factor) # factor=8 downsamples original imgs by 8x
  File "/nerf-pytorch/load_llff.py", line 114, in _load_data
    imgs = imgs = [imread(f)[...,:3]/255. for f in imgfiles]
  File "/nerf-pytorch/load_llff.py", line 114, in <listcomp>
    imgs = imgs = [imread(f)[...,:3]/255. for f in imgfiles]
  File "/nerf-pytorch/load_llff.py", line 110, in imread
    return imageio.imread(f, ignoregamma=True)
  File "/usr/local/lib/python3.8/dist-packages/imageio/__init__.py", line 97, in imread
    return imread_v2(uri, format=format, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/imageio/v2.py", line 360, in imread
    result = file.read(index=0, **kwargs)
TypeError: read() got an unexpected keyword argument 'ignoregamma'
```

This issue is similar to [Issue #190](https://github.com/bmild/nerf/issues/190) in the original `bmild/nerf` repository, which is implemented based on Tensorflow (but not PyTorch).
Similar with this, to resolve it, update [line 110 of load_llff.py](https://github.com/yenchenlin/nerf-pytorch/blob/63a5a630c9abd62b0f21c08703d0ac2ea7d4b9dd/load_llff.py#L110) as follows:
```python
            return imageio.imread(f, apply_gamma=True)
```
I hope this helps!

**Comment by ash0923** [comment]
Updating the version of imageio to 2.9.0 also resolved the issue.

**Comment by LunaBright** [comment]
update line 110 of load_llff.py as follows can also solve:
`return imageio.read(f,format="PNG-PIL",ignoregamma=True)`
