### ISSUE TITLE
TypeError: type torch.cuda.FloatTensor not available. Torch not compiled with CUDA enabled.

### ISSUE THREAD

**Issue by ohjarwa** [yenchenlin/nerf-pytorch#48]
detail on traceback：
Traceback (most recent call last):
  File "F:\fuxian\nerf-pytorch\run_nerf.py", line 876, in <module>
    torch.set_default_tensor_type('torch.cuda.FloatTensor')
  File "F:\Program\Anaconda3\lib\site-packages\torch\__init__.py", line 321, in set_default_tensor_type
    _C._set_default_tensor_type(t)

This error occurs after ' python run_nerf.py --config configs/lego.txt'
How to solve it?

**Comment by ohjarwa** [comment]
check torch version in base environment
