### ISSUE TITLE
No valid H.264 encoder was found with the ffmpeg installation

### ISSUE THREAD

**Issue by flybiubiu** [yenchenlin/nerf-pytorch#97]
Thx!
Awesome work!

Done, saving (40, 400, 400, 3) (40, 400, 400)█████████████████████████████████████████████████████████| 40/40 [05:47<00:00,  8.68s/it]
 25%|████████████████████▏                                                            | 49999/200000 [2:04:07<6:12:22,  6.71it/s]
Traceback (most recent call last):
  File "run_nerf.py", line 878, in <module>
    train()
  File "run_nerf.py", line 808, in train
    imageio.mimwrite(moviebase + 'rgb.mp4', to8b(rgbs), fps=30, quality=8)
  File "/home/ubuntu/anaconda3/envs/nerf/lib/python3.8/site-packages/imageio/v2.py", line 331, in mimwrite
    return file.write(ims, **kwargs)
  File "/home/ubuntu/anaconda3/envs/nerf/lib/python3.8/site-packages/imageio/core/legacy_plugin_wrapper.py", line 229, in write
    writer.append_data(image)
  File "/home/ubuntu/anaconda3/envs/nerf/lib/python3.8/site-packages/imageio/core/format.py", line 589, in append_data
    return self._append_data(im, total_meta)
  File "/home/ubuntu/anaconda3/envs/nerf/lib/python3.8/site-packages/imageio/plugins/ffmpeg.py", line 600, in _append_data
    self._initialize()
  File "/home/ubuntu/anaconda3/envs/nerf/lib/python3.8/site-packages/imageio/plugins/ffmpeg.py", line 658, in _initialize
    self._write_gen.send(None)
  File "/home/ubuntu/anaconda3/envs/nerf/lib/python3.8/site-packages/imageio_ffmpeg/_io.py", line 503, in write_frames
    codec = get_first_available_h264_encoder()
  File "/home/ubuntu/anaconda3/envs/nerf/lib/python3.8/site-packages/imageio_ffmpeg/_io.py", line 130, in get_first_available_h264_encoder
    raise RuntimeError(
RuntimeError: No valid H.264 encoder was found with the ffmpeg installation

**Comment by flybiubiu** [comment]
done

**Comment by HkDzl** [comment]
How did you solve it? Thank you!

**Comment by HkDzl** [comment]
> ho

How did you solve it? Thank you

**Comment by flybiubiu** [comment]
I have a slight memory that ffmpeg's version
